SGPC/ViewModels/TicketViewModel.cs
using SGPC.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SGPC.ViewModels
{
	public class TicketViewModel
	{


		[Display(Name = "Name", ResourceType = typeof(TicketResource))]
		public string Name { get; set; }
		[Display(Name = "Subject", ResourceType = typeof(TicketResource))]
		public string Subject { get; set; }

		[Display(Name = "Description", ResourceType = typeof(TicketResource))]
		public string Description { get; set; }

		[Display(Name = "Address", ResourceType = typeof(TicketResource))]
		public string Address { get; set; }

		[Display(Name = "Address", ResourceType = typeof(TicketResource))]
		public string ReferBy { get; set; }

		public string Contact { get; set; }


		public string PhoneNo { get; set; }

		[Display(Name = "MobileNo", ResourceType = typeof(TicketResource))]
		public string MobileNo { get; set; }


		[Display(Name = "Status", ResourceType = typeof(TicketResource))]
		public int Status { get; set; }

		public Guid Id { get; set; }
	}
}

SGPC/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Database.Services.Repository.UnitsOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using SGPC.EF.Models;
using SGPC.ViewModels;

namespace SGPC.Controllers
{
    public class TicketController : Controller
    {

		private readonly IStringLocalizer<HomeController> _localizer;
		private readonly IUnitOfWork _unitOfWork;
		public TicketController(
			IStringLocalizer<HomeController> localizer,
			IUnitOfWork unitOfWork

			)
		{
			_localizer = localizer;
			_unitOfWork = unitOfWork;
		}

		public IActionResult Index()
		{
			List<TicketViewModel> _list = AutoMapper.Mapper.Map<List<TicketViewModel>>(_unitOfWork.tickets.GetAll().ToList());
			return View(_list);
		}


		public IActionResult Detail(Guid id) {
			TicketViewModel ticket;
			if (id != Guid.Empty)
			{
				ticket = AutoMapper.Mapper.Map<TicketViewModel>(_unitOfWork.tickets.GetFirstOrDefault(t => t.Id == id));
				return View(ticket);
			}

			return NotFound();
		}


		public IActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Add(TicketViewModel ticketViewModel)
		{
			if (ModelState.IsValid)
			{
				try
				{
					Ticket ticket = AutoMapper.Mapper.Map<Ticket>(ticketViewModel);
					_unitOfWork.tickets.Add(ticket);
					_unitOfWork.SaveChanges();
					return View(ticketViewModel);
				}
				catch (Exception ex) {
					return View(ticketViewModel);
				}
			}
			return View(ticketViewModel);
		}
	}
}

SGPC/Views/Ticket/Add.cshtml
@namespace SGPC.Resources
@model SGPC.ViewModels.TicketViewModel


@{
	ViewData["Title"] = "Add";
}

<h2>Add</h2>
<div class="row">
	<div class="col-md-4">
		<form asp-action="Add">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Subject" class="control-label"></label>
				<input asp-for="Subject" class="form-control" />
				<span asp-validation-for="Subject" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Address" class="control-label"></label>
				<input asp-for="Address" class="form-control" />
				<span asp-validation-for="Address" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ReferBy" class="control-label"></label>
				<input asp-for="ReferBy" class="form-control" />
				<span asp-validation-for="ReferBy" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Contact" class="control-label"></label>
				<input asp-for="Contact" class="form-control" />
				<span asp-validation-for="Contact" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="PhoneNo" class="control-label"></label>
				<input asp-for="PhoneNo" class="form-control" />
				<span asp-validation-for="PhoneNo" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="MobileNo" class="control-label"></label>
				<input asp-for="MobileNo" class="form-control" />
				<span asp-validation-for="MobileNo" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="@Common.Save" class="btn btn-default" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SGPC/Views/Ticket/Detail.cshtml
@using SGPC.Resources
@using SGPC.Helpers
@model SGPC.ViewModels.TicketViewModel
@{
	ViewData["Title"] = "Detail";
}

<fieldset>
	<legend><h2>Detail</h2></legend>
	<form asp-action="Detail" asp-controller="Ticket">
	
		<table width="100%">

			<tr>
				<td>@TicketResource.Status</td>
				<td>
					<select asp-for="@Model.Status" asp-items="@SGPC.Helpers.Common.GetEnumTicketStatus(Model.Status)"></select>
				</td>
			</tr>

			<tr>
				<td>@TicketResource.Name</td>
				<td>@Model.Name</td>
			</tr>
			<tr>
				<td>@TicketResource.Subject</td>
				<td>@Model.Subject</td>
			</tr>
			<tr>
				<td>@TicketResource.ReferBy</td>
				<td>@Model.ReferBy</td>


			</tr>
			<tr>
				<td>@TicketResource.Status</td>
				<td>@Model.Status</td>
			</tr>
			<tr>
				<td>@TicketResource.Description</td>
				<td>@Model.Description</td>
		</tr>


		</table>

	
	</form>

</fieldset>

SGPC/Views/Ticket/Index.cshtml
@namespace SGPC.Resources
@model IEnumerable<SGPC.ViewModels.TicketViewModel>

@{
	ViewData["Title"] = "Ticket List";
}

<h4>TicketViewModel</h4>
<hr />
<div class="row">
	<div class="col-md-12">
		<table width="100%">
			<tr>
				<th>@TicketResource.Name</th>
				<th>@TicketResource.Subject</th>
				<th>@TicketResource.ReferBy</th>
				<th>@TicketResource.Contact</th>
				<th>@TicketResource.Status</th>
				<th>@Common.Detail</th>

			</tr>

			@if (Model != null)
			{
			@foreach (var ticket in Model)
			{
			<tr>
				<td>@ticket.Name</td>
				<td>@ticket.Subject</td>
				<td>@ticket.ReferBy</td>
				<td>@ticket.Contact</td>
				<td>@ticket.Status</td>
				<td><a asp-action="Detail" asp-controller="Ticket" asp-route-id="@ticket.Id" /> @Common.Detail</td>
			</tr>
			}
			}
		</table>

	</div>
</div>